<?php

require "vendor/autoload.php";

$configs = array(
    "services"=>array(
        "database" => "redis://127.0.0.1:6379",
        "storage" => "filesystem:// /tmp"
    ),
    "default_objects"=>array(
        "graph" => class_exists(\PhoNetworksAutogenerated\Twitter::class) ? \PhoNetworksAutogenerated\Twitter::class : ( class_exists(\PhoNetworksAutogenerated\Facebook::class) ? \PhoNetworksAutogenerated\Facebook::class : \PhoNetworksAutogenerated\Graph::class ),
  		"founder" => \PhoNetworksAutogenerated\User::class
    )
);

$kernel = new \Pho\Kernel\Kernel($configs);
$founder = new \PhoNetworksAutogenerated\User($kernel, $kernel->space(), "123456");
$kernel->boot($founder);

echo "Graph:".(string) $kernel->graph()->id()."\n";
echo "Founder:".(string) $kernel->founder()->id()."\n";

$server = new \Pho\Server\Rest\Daemon($kernel);
$server->setPort(1337);
//eval(\Psy\sh());
$server->serve();
