<?php

require "vendor/autoload.php";
/*
include("src/Pho/Server/Controllers/AbstractController.php");
include("src/Pho/Server/Controllers/EntityController.php");
include("src/Pho/Server/Controllers/NodeController.php");
include("src/Pho/Server/Controllers/KernelController.php");
include("src/Pho/Server/Server.php");
include("src/Pho/Server/Daemon.php");
*/
spl_autoload_register(function ($class_name) {
  if(strpos($class_name,"Pho\\Server\\Rest\\")!==0)
    return;
  $class_name = str_replace("\\", "/", substr($class_name, strlen("Pho\\Server\\Rest\\")));
  $class_file = __DIR__."/src/Pho/Server/Rest/".$class_name.".php";
  if(file_exists($class_file))
    include($class_file);
});

$configs = array(
    "services"=>array(
        "database" => "redis://127.0.0.1:6379",
        "storage" => "filesystem:// /tmp"
    ),
    "default_objects"=>array(
        "graph" => class_exists(\PhoNetworksAutogenerated\Twitter::class) ? \PhoNetworksAutogenerated\Twitter::class : ( class_exists(\PhoNetworksAutogenerated\Facebook::class) ? \PhoNetworksAutogenerated\Facebook::class : \PhoNetworksAutogenerated\Graph::class ),
  		"founder" => \PhoNetworksAutogenerated\User::class
    )
);

$kernel = new \Pho\Kernel\Kernel($configs);
$founder = new \PhoNetworksAutogenerated\User($kernel, $kernel->space(), "123456");
$kernel->boot($founder);

echo "Graph:".(string) $kernel->graph()->id()."\n";
echo "Founder:".(string) $kernel->founder()->id()."\n";

$server = new \Pho\Server\Rest\Daemon($kernel);
$server->setPort(1337);
//eval(\Psy\sh());
$server->serve();
